apiVersion: batch/v1
kind: CronJob
metadata:
  name: devops
spec:
  schedule: "*/5 * * * *" # To define the schedule
  jobTemplate: # To define the job 
    spec:
      template:
        spec:
          containers:
          - name: cron-devops
            image: httpd:latest
            command: # To define what the container does when the cronjob is scheduled
            - echo "Welcome to xfusioncorp!"
          restartPolicy: OnFailure