apiVersion: v1
kind: Pod
metadata:
  name: secret-xfusion
spec:
   containers:
     - name: secret-container-xfusion
       image: centos:latest
       command: ['/bin/bash', '-c', 'sleep 10000']
       volumeMounts:
         - mountPath: "/opt/cluster"
           name: secret-volume-xfusion
           readOnly: true
   volumes:
     - name: secret-volume-xfusion
       projected:
        sources:
          - secret:
              name: ecommerce